export const tradeTypes = [
  'Carpenter',
  'Bricklayer / Mason',
  'Drywall Installer / Finisher',
  'Tiler',
  'Flooring Installer',
  'Concrete Finisher',
  'Roofer',
  'Insulation Worker',
  'Painter and Decorator',
  'Glazier (glass/window installation)',
  'Plasterer',
  'Electrician',
  'Plumber',
  'HVAC Technician (Heating, Ventilation, and Air Conditioning)',
  'Boilermaker',
  'Mechanical Installer',
  'Automation Technician',
  'Welder',
  'Ironworker',
  'Sheet Metal Worker',
  'Machinist',
  'Heavy Equipment Operator',
  'Crane Operator',
  'Rigger',
  'Scaffolder',
  'Construction Manager',
  'Construction Inspector',
  'Landscaper',
  'Gardener',
  'Tree Surgeon / Arborist',
  'Agricultural Technician',
  'Farmer',
  'Elevator Mechanic',
  'Consultant',
  'Carpet Installer',
  'Security System Installer',
  'Smart Home Technician',
  'Solar Panel Installer',
  'Wind Turbine Technician',
  'Energy Efficiency Consultant',
  'Auto Mechanic',
  'Aircraft Mechanic',
  'Transporter / Delivery / HGV Driver'
];
